name: Build and Release

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os:
          # - windows-latest
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Latest Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        id: build
        shell: bash
        run: |
          if [[ "${RUNNER_OS}" == "Linux" ]]; then
            echo "Installing libudev-dev"
            sudo apt-get update
            sudo apt-get install libudev-dev
          fi

          cargo build --all --release --locked

          binary_extension=""
          if [[ "${RUNNER_OS}" == "Windows" ]]; then
            echo "Binary extension is Windows"
            binary_extension=".exe"
          fi

          if [[ "${RUNNER_OS}" == "macOS" ]]; then
            echo "Runner is mac Os"
            binary_path="ci-test-macos-intel-latest${binary_extension}"
          else
            echo "Runner is $matrix.os"
            binary_path="ci-test-${{ matrix.os }}${binary_extension}"
          fi
          echo "Current Binary path is $binary_path"
          mv "target/release/ci-test${binary_extension}" "${binary_path}"
          echo "Setting output"
          echo "::set-output name=binary_path::${binary_path}"
          echo "Stripping Binary Path"
          strip "${binary_path}"

      - name: Release Tags
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.build.outputs.binary_path }}
